# Generated by Django 4.0.2 on 2022-02-25 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('bundle', models.FileField(upload_to='', verbose_name='Windows Bundle')),
                ('description', models.TextField(max_length=400)),
                ('author', models.CharField(max_length=25)),
                ('X offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Y offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Z offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Rotation along Y', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
            ],
        ),
    ]
