# Generated by Django 4.0.2 on 2022-02-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bundle',
            field=models.TextField(verbose_name='Encoded File'),
        ),
    ]
