# Generated by Django 4.0.2 on 2022-03-10 10:50

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0004_project_asset_name_alter_project_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=40)),
                ('hex_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40, unique=True)),
                ('model_base', models.TextField(default='empty')),
                ('placeable', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='Rotation along Y',
        ),
        migrations.RemoveField(
            model_name='project',
            name='X offset',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Y offset',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Z offset',
        ),
        migrations.RemoveField(
            model_name='project',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='project',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Not deployed', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Y offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Z offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('X Rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('Y Rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('Z Rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('X scale', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('Y scale', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('Z scale', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('model_file', models.ManyToManyField(max_length=1, to='bundler.ModelFile')),
                ('project', models.ManyToManyField(max_length=1, to='bundler.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='material_prefixes',
            field=models.ManyToManyField(to='bundler.MaterialPrefix'),
        ),
        migrations.AddField(
            model_name='project',
            name='model_files',
            field=models.ManyToManyField(to='bundler.ModelFile'),
        ),
    ]
