# Generated by Django 4.0.2 on 2022-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0006_material_alter_materialprefix_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwappableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Swappable Groups',
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Colors'},
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='group',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='group',
            field=models.ManyToManyField(max_length=1, to='bundler.SwappableGroup'),
        ),
    ]
