# Generated by Django 4.0.2 on 2022-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0007_swappablegroup_alter_material_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfile',
            old_name='model_name',
            new_name='hidden_name',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='presentable_name',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
