# Generated by Django 4.0.2 on 2022-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0008_rename_model_name_modelfile_hidden_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialprefix',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swappablegroup',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
