# Generated by Django 4.0.2 on 2022-04-08 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0009_material_connected_materialprefix_connected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSubConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Y offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Z offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('X Rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('Y Rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('Z Rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
            ],
            options={
                'verbose_name_plural': 'Model SubConfigurations',
            },
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='model_configurations',
            field=models.ManyToManyField(to='bundler.ModelConfiguration'),
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='sub_configurations',
            field=models.ManyToManyField(max_length=6, to='bundler.ModelSubConfiguration'),
        ),
    ]
