# Generated by Django 4.0.2 on 2022-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0010_modelsubconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfiguration',
            name='sub_configurations',
            field=models.ManyToManyField(blank=True, max_length=6, to='bundler.ModelSubConfiguration'),
        ),
    ]
