# Generated by Django 4.0.2 on 2022-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0011_alter_modelconfiguration_sub_configurations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='model_file',
            new_name='model_file_ref',
        ),
        migrations.AlterField(
            model_name='modelconfiguration',
            name='X offset',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='posX'),
        ),
    ]
