# Generated by Django 4.0.2 on 2022-04-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0012_rename_model_file_modelconfiguration_model_file_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='model_file_ref',
            new_name='ModelFileRef',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='X Rotation',
            new_name='X Rotation (sub)',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='X offset',
            new_name='X offset (sub)',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Y Rotation',
            new_name='Y Rotation (sub)',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Y offset',
            new_name='Y offset (sub)',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Z Rotation',
            new_name='Z Rotation (sub)',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Z offset',
            new_name='Z offset (sub)',
        ),
    ]
