# Generated by Django 4.0.2 on 2022-04-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0013_rename_model_file_ref_modelconfiguration_modelfileref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='ModelFileRef',
            new_name='model_file_ref',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='X offset',
            new_name='posX',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='Y offset',
            new_name='posY',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='Z offset',
            new_name='posZ',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='X Rotation',
            new_name='rotX',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='Y Rotation',
            new_name='rotY',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='Z Rotation',
            new_name='rotZ',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='X scale',
            new_name='scaleX',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='Y scale',
            new_name='scaleY',
        ),
        migrations.RenameField(
            model_name='modelconfiguration',
            old_name='Z scale',
            new_name='scaleZ',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='X offset (sub)',
            new_name='subPosX',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Y offset (sub)',
            new_name='subPosY',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Z offset (sub)',
            new_name='subPosZ',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='X Rotation (sub)',
            new_name='subRotX',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Y Rotation (sub)',
            new_name='subRotY',
        ),
        migrations.RenameField(
            model_name='modelsubconfiguration',
            old_name='Z Rotation (sub)',
            new_name='subRotZ',
        ),
    ]
